# Generated by Django 5.0.14 on 2026-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seconds_studied', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Kunlik o'qish",
                'verbose_name_plural': "Kunlik o'qishlar",
                'ordering': ['-date'],
            },
        ),
    ]
