# Generated by Django 6.0.6 on 2026-06-14 10:45

from django.db import migrations

def migrate_conversations(apps, schema_editor):
    Conversation = apps.get_model('chat', 'Conversation')
    Channel = apps.get_model('chat', 'Channel')
    ChannelMember = apps.get_model('chat', 'ChannelMember')
    Message = apps.get_model('chat', 'Message')

    for convo in Conversation.objects.all():
        participants = list(convo.participants.all())
        if not participants:
            continue
        
        # Determine creator and name
        creator = participants[0]
        names = [f"{u.first_name} {u.last_name}".strip() or u.username for u in participants]
        name = " & ".join(names)

        # Create the Channel
        channel = Channel.objects.create(
            name=name[:100],
            channel_type='direct',
            creator=creator,
            created_at=convo.created_at
        )

        # Create members
        for user in participants:
            ChannelMember.objects.create(
                channel=channel,
                user=user,
                role='member',
                joined_at=convo.created_at
            )

        # Link messages to the new channel and copy content to text
        messages_to_update = Message.objects.filter(conversation=convo)
        for msg in messages_to_update:
            msg.channel = channel
            msg.text = msg.content or ""
            msg.save()

def reverse_migrate_conversations(apps, schema_editor):
    # Reverse logic is optional, but we can write a basic one or pass
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_message_edited_at_message_file_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_conversations, reverse_migrate_conversations),
    ]
