# Generated by Django 5.0.14 on 2026-06-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_conversation_remove_message_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/logos/%Y/%m/'),
        ),
    ]
