# Generated by Django 6.0.6 on 2026-06-14 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


from django.db.models import Q

def clean_empty_phones(apps, schema_editor):
    User = apps.get_model('users', 'User')
    qs = User.objects.filter(Q(phone='') | Q(phone__isnull=True))
    for idx, user in enumerate(qs):
        user.phone = f"+998000000{idx:03d}"
        user.save(update_fields=['phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.RunPython(clean_empty_phones),
        migrations.AlterField(

            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
