# Generated by Django 5.0.14 on 2026-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question_answeroption_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
