# Generated by Django 5.0.14 on 2026-06-13 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_learning_outcomes_course_preview_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saqlangan kurs',
                'verbose_name_plural': 'Saqlangan kurslar',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
