# Generated by Django 6.0.6 on 2026-06-13 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_savedcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('file', 'Fayl (PDF, DOCX va h.k.)'), ('link', 'Tashqi havola')], default='file', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_resources/')),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Dars resursi',
                'verbose_name_plural': 'Dars resurslari',
                'ordering': ['order'],
            },
        ),
    ]
