# Generated by Django 6.0.6 on 2026-06-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lessonresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_deadline_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video dars'), ('text', 'Matn dars'), ('quiz', 'Test'), ('live', 'Live dars'), ('homework', 'Vazifa')], default='video', max_length=10),
        ),
    ]
