# Generated by Django 6.0.6 on 2026-06-13 13:45

from django.db import migrations


def set_quiz_lessons(apps, schema_editor):
    Lesson = apps.get_model('courses', 'Lesson')
    # Savoli bor darslarni quiz dars turiga o'tkazish
    for lesson in Lesson.objects.all():
        if lesson.questions.exists():
            lesson.lesson_type = 'quiz'
            lesson.save(update_fields=['lesson_type'])

def unset_quiz_lessons(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_homework_deadline_days_and_more'),
    ]

    operations = [
        migrations.RunPython(set_quiz_lessons, unset_quiz_lessons),
    ]
