# Generated by Django 6.0.6 on 2026-06-13 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20260613_1845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline_days', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('after_lesson', models.ForeignKey(blank=True, help_text="Qaysi darsdan keyin ko'rsatiladi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='courses.lesson')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='courses.course')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('file', 'Fayl'), ('link', 'Havola')], default='file', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='homework_resources/')),
                ('url', models.URLField(blank=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.homework')),
            ],
            options={
                'verbose_name': 'Vazifa resursi',
                'verbose_name_plural': 'Vazifa resurslari',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('submitted', 'Topshirilgan'), ('reviewed', "Ko'rib chiqilgan")], default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topshirilgan vazifa',
                'verbose_name_plural': 'Topshirilgan vazifalar',
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
