# Generated by Django 6.0.6 on 2026-06-14 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_homework_homeworkresource_homeworksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='type',
            field=models.CharField(choices=[('quiz', 'Test'), ('written', 'Yozma')], default='written', max_length=15),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='file_answer',
            field=models.FileField(blank=True, null=True, upload_to='hw_submissions/'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='quiz_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='teacher_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='text_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.homework'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('submitted', 'Topshirilgan'), ('reviewed', "Ko'rib chiqilgan")], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.lesson'),
        ),
    ]
