# Generated by Django 6.0.6 on 2026-06-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_enrollment', 'New Enrollment'), ('quiz_completed', 'Quiz Completed'), ('homework_submitted', 'Homework Submitted'), ('new_message', 'New Message'), ('homework_reviewed', 'Homework Reviewed')], max_length=30),
        ),
    ]
