# Generated by Django 6.0.6 on 2026-06-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_link_notification_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_enrollment', 'New Enrollment'), ('quiz_completed', 'Quiz Completed'), ('homework_submitted', 'Homework Submitted'), ('new_message', 'New Message'), ('homework_reviewed', 'Homework Reviewed'), ('enrollment_request', "Yozilish so'rovi"), ('enrollment_approved', 'Yozilish tasdiqlandi'), ('enrollment_rejected', 'Yozilish rad etildi')], max_length=30),
        ),
    ]
