# Generated by Django 5.0.14 on 2026-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_enrollment', 'New Enrollment'), ('quiz_completed', 'Quiz Completed'), ('homework_submitted', 'Homework Submitted'), ('new_message', 'New Message'), ('homework_reviewed', 'Homework Reviewed'), ('enrollment_request', "Yozilish so'rovi"), ('enrollment_approved', 'Yozilish tasdiqlandi'), ('enrollment_rejected', 'Yozilish rad etildi'), ('level_up', 'Level Up')], max_length=30),
        ),
    ]
